### ISSUE TITLE
Why another port?

### ISSUE THREAD

**Issue by leeoniya** [phaserjs/phaser-box2d#1]
hey @photonstorm,

it would be great if the readme would address the elephant in the room: why another port?

- https://github.com/piqnt/planck.js
- https://github.com/kripken/box2d.js
- https://github.com/lusito/box2d.ts

e.g. do we get better performance? (i recall you writing about the additional optimizations you had to do a few years ago, but cannot find the blog/markdown now). some benchmarks would help!

thanks!

**Comment by photonstorm** [comment]
Because we converted Box2D version 3. Those are the old v2 ports.

v3 has enough really nice new things in it as-is. The new Soft Step Solver is really, really lovely and far more stable than v2 (by Erin's own admission, that isn't my claim). Precision is much better, Joints got a big overhaul, Capsules (rounded bodies) are new and lovely, and most important of all the speculative collision is redone from scratch (no gaps between polys, minimal time loss, bullet support). CCD is just sweet in v3. All of these things alone warranted the conversion imho.

**Comment by leeoniya** [comment]
ah, nice. i guess for people who dont keep up to date on box2d versions, this isnt super obvious, even though it does say v3! still, a note in the readme about the other ports being box2d v2 would be useful as an explicit call-out.

**Comment by mreinstein** [comment]
It's also nice to see a box2d port that is being hosted by phaser, which has shown a lot more staying power than these other various one-off random port maintainers.  One can hope that phaser will be able to put resources into keeping this maintained over time, which has been a big problem for the box2d js ports in general. :)
